<?php

use Drupal\Core\File\FileSystemInterface;
use Drupal\views\Views;

/**
 * Implements hook_page_attachments().
 */
function recalendar_page_attachments(array &$page) {
  if (Drupal::routeMatch()->getRouteName() == 'recalendar.events') {
    $page['#attached']['library'][] = 'recalendar/eventscalendar';
  }
}

/**
 * Implements hook_cron().
 */
function recalendar_cron(): void {
  $view_events = Views::getView('recalendar', );
  $view_events->setDisplay('rest_export_1');

  $directory = 'public://data/';

  Drupal::service('file_system')->prepareDirectory(
    $directory,
    FileSystemInterface::CREATE_DIRECTORY
  );

  $view_events_out = $view_events->render();
  $events = (string) $view_events_out['#markup'];

  Drupal::service('file_system')->saveData(
    $events,
    $directory . 'data_export_events.json',
    FileSystemInterface::EXISTS_REPLACE
  );
}
